export type Language = "en" | "tr" | "ar";

export type LocalizedText = Record<Language, string>;

export type AnimalProfile = {
  id: string;
  name: LocalizedText;
  tags: ReadonlySet<string>;
  uncertainTags: ReadonlySet<string>;
  prior: number;
};

export type Question = {
  id: string;
  text: LocalizedText;
  clarity: number;
};

type AnimalRow = [
  id: string,
  en: string,
  tr: string,
  ar: string,
  tags: string,
  uncertainTags?: string,
  prior?: number,
];

const q = (id: string, en: string, tr: string, ar: string, clarity = 0.98): Question => ({
  id,
  text: { en, tr, ar },
  clarity,
});

// Every question describes one observable axis. Ambiguous value judgements and
// compound questions are deliberately excluded from this catalog.
export const QUESTIONS: readonly Question[] = [
  q("mammal", "Is it a mammal?", "Memeli mi?", "هل هو من الثدييات؟"),
  q("bird", "Is it a bird?", "Bir kuş mu?", "هل هو طائر؟"),
  q("reptile", "Is it a reptile?", "Bir sürüngen mi?", "هل هو من الزواحف؟"),
  q("amphibian", "Is it an amphibian?", "Bir amfibi mi?", "هل هو من البرمائيات؟"),
  q("fish", "Is it a fish?", "Bir balık mı?", "هل هو سمكة؟"),
  q("insect", "Is it an insect?", "Bir böcek mi?", "هل هو من الحشرات؟"),
  q("arachnid", "Is it an arachnid?", "Örümceğimsilerden mi?", "هل هو من العنكبيات؟"),
  q("mollusk", "Is it a mollusk?", "Bir yumuşakça mı?", "هل هو من الرخويات؟"),
  q("crustacean", "Is it a crustacean?", "Bir kabuklu deniz canlısı mı?", "هل هو من القشريات؟"),
  q("extinct", "Is it extinct?", "Nesli tükenmiş mi?", "هل هو منقرض؟"),
  q("mainly_aquatic", "Does it spend most of its life in water?", "Hayatının çoğunu suda mı geçirir?", "هل يقضي معظم حياته في الماء؟"),
  q("marine", "Does it normally live in the sea?", "Normalde denizde mi yaşar?", "هل يعيش عادة في البحر؟"),
  q("freshwater", "Does it normally live in fresh water?", "Normalde tatlı suda mı yaşar?", "هل يعيش عادة في المياه العذبة؟"),
  q("semi_aquatic", "Is it equally at home on land and in water?", "Hem karada hem suda yaşamaya uyumlu mu?", "هل يتكيف مع العيش في البر والماء؟", 0.94),
  q("flies", "Can a typical adult fly under its own power?", "Tipik bir yetişkini kendi gücüyle uçabilir mi?", "هل يستطيع البالغ النموذجي الطيران بقوته؟"),
  q("flightless_bird", "Is it a flightless bird?", "Uçamayan bir kuş mu?", "هل هو طائر لا يطير؟"),
  q("arboreal", "Does it spend much of its life in trees?", "Yaşamının büyük bölümünü ağaçlarda mı geçirir?", "هل يقضي جزءا كبيرا من حياته على الأشجار؟", 0.94),
  q("burrows", "Does it commonly live in a burrow?", "Yaygın olarak bir kovukta mı yaşar?", "هل يعيش عادة في جحر؟", 0.94),
  q("domesticated", "Has it been widely domesticated by humans?", "İnsanlar tarafından yaygın biçimde evcilleştirilmiş mi?", "هل استأنسه البشر على نطاق واسع؟"),
  q("farm_animal", "Is it commonly raised on farms?", "Çiftliklerde yaygın olarak yetiştirilir mi?", "هل يربى عادة في المزارع؟"),
  q("predator", "Does it normally hunt other animals for food?", "Beslenmek için normalde başka hayvanları avlar mı?", "هل يصطاد عادة حيوانات أخرى للغذاء؟", 0.95),
  q("herbivore", "Is its natural diet mostly plants?", "Doğal beslenmesi çoğunlukla bitkilerden mi oluşur?", "هل يتكون غذاؤه الطبيعي غالبا من النباتات؟", 0.95),
  q("omnivore", "Does it naturally eat both plants and animals?", "Doğal olarak hem bitkisel hem hayvansal besin yer mi?", "هل يأكل طبيعيا النباتات والحيوانات معا؟", 0.94),
  q("tiny", "Could a typical adult fit in one hand?", "Tipik bir yetişkini tek ele sığar mı?", "هل يمكن أن يتسع البالغ النموذجي في يد واحدة؟", 0.93),
  q("large", "Is a typical adult larger than a person?", "Tipik bir yetişkini insandan büyük mü?", "هل البالغ النموذجي أكبر من الإنسان؟", 0.94),
  q("gigantic", "Is a typical adult heavier than a car?", "Tipik bir yetişkini bir otomobilden ağır mı?", "هل البالغ النموذجي أثقل من سيارة؟", 0.94),
  q("fur", "Is its body visibly covered in fur or hair?", "Vücudu belirgin biçimde kürk veya kılla kaplı mı?", "هل يغطي جسمه فرو أو شعر واضح؟"),
  q("feathers", "Is its body covered in feathers?", "Vücudu tüylerle kaplı mı?", "هل يغطي جسمه الريش؟"),
  q("scales", "Is most of its body covered in scales?", "Vücudunun çoğu pullarla mı kaplı?", "هل تغطي الحراشف معظم جسمه؟", 0.96),
  q("shell", "Does it have a hard external shell?", "Sert bir dış kabuğu var mı?", "هل له صدفة خارجية صلبة؟"),
  q("exoskeleton", "Does it have a hard external skeleton?", "Sert bir dış iskeleti var mı?", "هل له هيكل عظمي خارجي صلب؟"),
  q("no_legs", "Does it naturally have no legs?", "Doğal olarak bacaksız mı?", "هل هو بلا أرجل طبيعيا؟"),
  q("two_legs", "Does it normally move on two legs?", "Normalde iki bacak üzerinde mi hareket eder?", "هل يتحرك عادة على ساقين؟"),
  q("four_legs", "Does it normally have four legs?", "Normalde dört bacağı var mı?", "هل له عادة أربع أرجل؟"),
  q("six_legs", "Does it have six legs?", "Altı bacağı var mı?", "هل له ست أرجل؟"),
  q("eight_legs", "Does it have eight walking legs?", "Sekiz yürüme bacağı var mı?", "هل له ثماني أرجل للمشي؟"),
  q("webbed_feet", "Does it have webbed feet?", "Perdeli ayakları var mı?", "هل له أقدام مكففة؟"),
  q("hooves", "Does it have hooves?", "Toynakları var mı?", "هل له حوافر؟"),
  q("horns", "Does it have permanent horns?", "Kalıcı boynuzları var mı?", "هل له قرون دائمة؟"),
  q("antlers", "Do males normally grow branching antlers?", "Erkeklerinde normalde dallanan boynuzlar çıkar mı?", "هل تنمو للذكور عادة قرون متشعبة؟"),
  q("trunk", "Does it have a muscular trunk?", "Kaslı bir hortumu var mı?", "هل له خرطوم عضلي؟"),
  q("long_neck", "Is it especially known for a very long neck?", "Özellikle çok uzun boynuyla mı bilinir?", "هل يشتهر خصوصا برقبته الطويلة جدا؟"),
  q("pouch", "Do females carry young in a pouch?", "Dişileri yavrularını bir kesede taşır mı?", "هل تحمل الإناث صغارها في جراب؟"),
  q("spines", "Is its body protected by prominent spines or quills?", "Vücudu belirgin dikenlerle korunuyor mu?", "هل يحمي جسمه شوك بارز؟"),
  q("stripes", "Is it strongly associated with natural stripes?", "Doğal çizgileriyle güçlü biçimde özdeşleşmiş mi?", "هل يشتهر بخطوط طبيعية واضحة؟"),
  q("spots", "Is it strongly associated with a spotted coat or skin?", "Benekli kürkü veya derisiyle güçlü biçimde özdeşleşmiş mi?", "هل يشتهر بجلد أو فرو مرقط؟"),
  q("black_white", "Is it characteristically black and white?", "Karakteristik olarak siyah-beyaz mı?", "هل لونه المميز أسود وأبيض؟"),
  q("venomous", "Can it inject venom by biting or stinging?", "Isırarak veya sokarak zehir enjekte edebilir mi?", "هل يستطيع حقن السم بالعض أو اللسع؟"),
  q("tentacles", "Does it have prominent tentacles or flexible arms?", "Belirgin dokunaçları veya esnek kolları var mı?", "هل له مجسات أو أذرع مرنة بارزة؟"),
  q("claws", "Is it especially known for large claws or pincers?", "Özellikle büyük pençe veya kıskaçlarıyla mı bilinir?", "هل يشتهر بمخالب أو كماشات كبيرة؟"),
  q("color_change", "Can it deliberately change its skin color for camouflage or signalling?", "Kamuflaj veya iletişim için deri rengini değiştirebilir mi?", "هل يستطيع تغيير لون جلده للتمويه أو التواصل؟"),
  q("echolocation", "Does it use echolocation to navigate or hunt?", "Yön bulmak veya avlanmak için ekolokasyon kullanır mı?", "هل يستخدم تحديد الموقع بالصدى للتنقل أو الصيد؟"),
  q("lays_eggs", "Does it lay eggs?", "Yumurta bırakır mı?", "هل يبيض؟"),
  q("marsupial", "Is it a marsupial?", "Keseli bir memeli mi?", "هل هو من الجرابيات؟"),
  q("primate", "Is it a primate?", "Bir primat mı?", "هل هو من الرئيسيات؟"),
  q("rodent", "Is it a rodent?", "Bir kemirgen mi?", "هل هو من القوارض؟"),
  q("cat_family", "Is it a member of the cat family?", "Kedigiller ailesinden mi?", "هل هو من فصيلة السنوريات؟"),
  q("canine_family", "Is it a member of the dog family?", "Köpekgiller ailesinden mi?", "هل هو من فصيلة الكلبيات؟"),
  q("bear_family", "Is it a member of the bear family?", "Ayıgiller ailesinden mi?", "هل هو من فصيلة الدببة؟"),
  q("whale_family", "Is it a whale or dolphin?", "Balina veya yunus grubundan mı?", "هل هو حوت أو دلفين؟"),
  q("ape", "Is it an ape rather than a monkey?", "Maymundan ziyade insansı maymun mu?", "هل هو من القردة العليا؟"),
  q("long_ears", "Is it known for unusually long external ears?", "Alışılmadık derecede uzun dış kulaklarıyla mı bilinir?", "هل يشتهر بأذنين خارجيتين طويلتين جدا؟"),
  q("hump", "Does it have one or more prominent humps?", "Bir veya daha fazla belirgin hörgücü var mı?", "هل له سنام بارز أو أكثر؟"),
  q("tusks", "Does it have prominent tusks?", "Belirgin fildişleri var mı?", "هل له أنياب بارزة؟"),
  q("reddish_fur", "Is it characteristically covered in reddish-orange fur?", "Karakteristik olarak kızıl-turuncu kürkle mi kaplı?", "هل يغطيه عادة فرو برتقالي محمر؟"),
  q("long_narrow_snout", "Does it have a distinctly long, narrow V-shaped snout?", "Belirgin biçimde uzun, dar ve V biçimli bir burnu var mı?", "هل له خطم طويل وضيق على شكل حرف V؟"),
  q("palmate_antlers", "Do males normally grow broad, palm-shaped antlers?", "Erkeklerinde normalde geniş, avuç biçimli boynuzlar çıkar mı?", "هل تنمو للذكور عادة قرون عريضة تشبه راحة اليد؟"),
  q("rat_sized_rodent", "Is it a rat-sized rodent, typically much heavier than a house mouse?", "Ev faresinden genellikle çok daha ağır, sıçan boyutunda bir kemirgen mi?", "هل هو قارض بحجم الجرذ وأثقل عادة بكثير من فأر المنزل؟", 0.96),
  q("slow", "Is it famously slow-moving?", "Yavaş hareket etmesiyle ünlü mü?", "هل يشتهر بالحركة البطيئة؟"),
  q("bioluminescent", "Can it naturally produce visible light?", "Doğal olarak görünür ışık üretebilir mi?", "هل يستطيع إنتاج ضوء مرئي طبيعيا؟"),
  q("regenerates_limbs", "Can it regrow complete lost limbs?", "Kaybettiği uzuvları tamamen yeniden büyütebilir mi?", "هل يستطيع إعادة إنماء أطراف كاملة؟"),
  q("electric", "Can it produce a strong electric discharge?", "Güçlü bir elektrik boşalması üretebilir mi?", "هل يستطيع إنتاج تفريغ كهربائي قوي؟"),
  q("filter_feeder", "Does it feed mainly by filtering tiny food from water?", "Çoğunlukla sudaki küçük besinleri süzerek mi beslenir?", "هل يتغذى أساسا بترشيح الغذاء الدقيق من الماء؟"),
];

const rows: readonly AnimalRow[] = [
  ["dog", "dog", "köpek", "كلب", "mammal domesticated omnivore fur four_legs canine_family"],
  ["cat", "cat", "kedi", "قط", "mammal domesticated predator fur four_legs cat_family"],
  ["lion", "lion", "aslan", "أسد", "mammal predator fur four_legs cat_family large"],
  ["tiger", "tiger", "kaplan", "نمر", "mammal predator fur four_legs cat_family large stripes"],
  ["leopard", "leopard", "leopar", "فهد مرقط", "mammal predator fur four_legs cat_family spots arboreal large"],
  ["cheetah", "cheetah", "çita", "فهد", "mammal predator fur four_legs cat_family spots large"],
  ["jaguar", "jaguar", "jaguar", "يغور", "mammal predator fur four_legs cat_family spots semi_aquatic large"],
  ["wolf", "wolf", "kurt", "ذئب", "mammal predator fur four_legs canine_family large"],
  ["fox", "fox", "tilki", "ثعلب", "mammal omnivore fur four_legs canine_family burrows"],
  ["hyena", "hyena", "sırtlan", "ضبع", "mammal predator fur four_legs large"],
  ["brown-bear", "brown bear", "boz ayı", "دب بني", "mammal omnivore fur four_legs bear_family large"],
  ["polar-bear", "polar bear", "kutup ayısı", "دب قطبي", "mammal predator fur four_legs bear_family large semi_aquatic"],
  ["giant-panda", "giant panda", "dev panda", "باندا عملاقة", "mammal herbivore fur four_legs bear_family black_white large"],
  ["elephant", "elephant", "fil", "فيل", "mammal herbivore four_legs trunk gigantic"],
  ["giraffe", "giraffe", "zürafa", "زرافة", "mammal herbivore four_legs hooves long_neck spots large"],
  ["zebra", "zebra", "zebra", "حمار وحشي", "mammal herbivore four_legs hooves stripes large"],
  ["horse", "horse", "at", "حصان", "mammal domesticated herbivore four_legs hooves farm_animal large"],
  ["donkey", "donkey", "eşek", "حمار", "mammal domesticated herbivore four_legs hooves farm_animal large long_ears"],
  ["cow", "cow", "inek", "بقرة", "mammal domesticated herbivore four_legs hooves horns farm_animal large"],
  ["goat", "goat", "keçi", "ماعز", "mammal domesticated herbivore four_legs hooves horns farm_animal"],
  ["sheep", "sheep", "koyun", "خروف", "mammal domesticated herbivore four_legs hooves horns farm_animal fur"],
  ["pig", "pig", "domuz", "خنزير", "mammal domesticated omnivore four_legs hooves farm_animal large"],
  ["camel", "camel", "deve", "جمل", "mammal domesticated herbivore four_legs hooves hump large"],
  ["deer", "deer", "geyik", "أيل", "mammal herbivore four_legs hooves antlers large"],
  ["moose", "moose", "sığın", "موظ", "mammal herbivore four_legs hooves antlers palmate_antlers large"],
  ["rhinoceros", "rhinoceros", "gergedan", "وحيد القرن", "mammal herbivore four_legs hooves horns gigantic"],
  ["hippopotamus", "hippopotamus", "su aygırı", "فرس النهر", "mammal herbivore four_legs semi_aquatic gigantic"],
  ["rabbit", "rabbit", "tavşan", "أرنب", "mammal herbivore fur four_legs burrows long_ears tiny"],
  ["hedgehog", "hedgehog", "kirpi", "قنفذ", "mammal omnivore four_legs spines tiny"],
  ["mouse", "mouse", "fare", "فأر", "mammal omnivore fur four_legs rodent burrows tiny"],
  ["rat", "rat", "sıçan", "جرذ", "mammal omnivore fur four_legs rodent burrows tiny rat_sized_rodent"],
  ["hamster", "hamster", "hamster", "هامستر", "mammal domesticated omnivore fur four_legs rodent burrows tiny"],
  ["squirrel", "squirrel", "sincap", "سنجاب", "mammal herbivore fur four_legs rodent arboreal tiny"],
  ["beaver", "beaver", "kunduz", "قندس", "mammal herbivore fur four_legs rodent semi_aquatic"],
  ["capybara", "capybara", "kapibara", "كابيبارا", "mammal herbivore fur four_legs rodent semi_aquatic large"],
  ["kangaroo", "kangaroo", "kanguru", "كنغر", "mammal herbivore two_legs marsupial pouch large"],
  ["koala", "koala", "koala", "كوالا", "mammal herbivore fur four_legs marsupial pouch arboreal"],
  ["wombat", "wombat", "vombat", "ومبت", "mammal herbivore fur four_legs marsupial pouch burrows"],
  ["platypus", "platypus", "ornitorenk", "خلد الماء", "mammal predator fur four_legs semi_aquatic lays_eggs venomous"],
  ["echidna", "echidna", "ekidne", "إكيدنا", "mammal predator four_legs spines lays_eggs tiny"],
  ["bat", "bat", "yarasa", "خفاش", "mammal predator fur flies echolocation tiny"],
  ["sloth", "sloth", "tembel hayvan", "كسلان", "mammal herbivore fur four_legs arboreal slow"],
  ["otter", "otter", "su samuru", "قضاعة", "mammal predator fur four_legs semi_aquatic"],
  ["seal", "seal", "fok", "فقمة", "mammal predator marine mainly_aquatic large"],
  ["walrus", "walrus", "mors", "فظ", "mammal predator marine mainly_aquatic large tusks"],
  ["dolphin", "dolphin", "yunus", "دلفين", "mammal predator marine mainly_aquatic whale_family echolocation large"],
  ["orca", "orca", "orka", "حوت قاتل", "mammal predator marine mainly_aquatic whale_family black_white gigantic"],
  ["blue-whale", "blue whale", "mavi balina", "حوت أزرق", "mammal marine mainly_aquatic whale_family gigantic filter_feeder"],
  ["chimpanzee", "chimpanzee", "şempanze", "شمبانزي", "mammal omnivore fur primate ape arboreal large"],
  ["gorilla", "gorilla", "goril", "غوريلا", "mammal herbivore fur primate ape four_legs large"],
  ["orangutan", "orangutan", "orangutan", "إنسان الغاب", "mammal omnivore fur primate ape arboreal large reddish_fur"],
  ["monkey", "monkey", "maymun", "قرد", "mammal omnivore fur primate arboreal"],
  ["penguin", "penguin", "penguen", "بطريق", "bird predator feathers two_legs flightless_bird marine semi_aquatic black_white lays_eggs"],
  ["ostrich", "ostrich", "deve kuşu", "نعامة", "bird omnivore feathers two_legs flightless_bird large lays_eggs"],
  ["kiwi", "kiwi", "kivi kuşu", "كيوي", "bird omnivore feathers two_legs flightless_bird tiny lays_eggs"],
  ["chicken", "chicken", "tavuk", "دجاج", "bird domesticated omnivore feathers two_legs farm_animal lays_eggs"],
  ["duck", "duck", "ördek", "بطة", "bird domesticated omnivore feathers two_legs flies semi_aquatic freshwater webbed_feet farm_animal lays_eggs"],
  ["goose", "goose", "kaz", "إوز", "bird domesticated herbivore feathers two_legs flies semi_aquatic freshwater webbed_feet farm_animal lays_eggs"],
  ["swan", "swan", "kuğu", "بجعة", "bird herbivore feathers two_legs flies semi_aquatic freshwater webbed_feet long_neck lays_eggs large"],
  ["eagle", "eagle", "kartal", "عقاب", "bird predator feathers two_legs flies claws lays_eggs large"],
  ["owl", "owl", "baykuş", "بومة", "bird predator feathers two_legs flies claws lays_eggs"],
  ["parrot", "parrot", "papağan", "ببغاء", "bird domesticated herbivore feathers two_legs flies arboreal lays_eggs"],
  ["pigeon", "pigeon", "güvercin", "حمامة", "bird domesticated herbivore feathers two_legs flies lays_eggs"],
  ["peacock", "peacock", "tavus kuşu", "طاووس", "bird omnivore feathers two_legs lays_eggs", "flies"],
  ["flamingo", "flamingo", "flamingo", "نحام", "bird omnivore feathers two_legs flies semi_aquatic webbed_feet long_neck lays_eggs large"],
  ["hummingbird", "hummingbird", "sinek kuşu", "طائر طنان", "bird herbivore feathers two_legs flies arboreal lays_eggs tiny"],
  ["toucan", "toucan", "tukan", "طوقان", "bird omnivore feathers two_legs flies arboreal lays_eggs"],
  ["puffin", "puffin", "deniz papağanı", "بفن", "bird predator feathers two_legs flies marine semi_aquatic webbed_feet lays_eggs"],
  ["crocodile", "crocodile", "timsah", "تمساح", "reptile predator scales four_legs semi_aquatic freshwater lays_eggs large long_narrow_snout"],
  ["alligator", "alligator", "aligator", "قاطع", "reptile predator scales four_legs semi_aquatic freshwater lays_eggs large"],
  ["snake", "snake", "yılan", "ثعبان", "reptile predator scales no_legs lays_eggs", "venomous"],
  ["cobra", "cobra", "kobra", "كوبرا", "reptile predator scales no_legs lays_eggs venomous"],
  ["turtle", "turtle", "kaplumbağa", "سلحفاة", "reptile herbivore scales four_legs shell slow lays_eggs", "mainly_aquatic"],
  ["sea-turtle", "sea turtle", "deniz kaplumbağası", "سلحفاة بحرية", "reptile herbivore scales four_legs shell marine mainly_aquatic lays_eggs large"],
  ["lizard", "lizard", "kertenkele", "سحلية", "reptile predator scales four_legs lays_eggs tiny"],
  ["chameleon", "chameleon", "bukalemun", "حرباء", "reptile predator scales four_legs arboreal color_change lays_eggs", "tiny"],
  ["iguana", "iguana", "iguana", "إغوانا", "reptile herbivore scales four_legs arboreal lays_eggs large"],
  ["frog", "frog", "kurbağa", "ضفدع", "amphibian predator four_legs semi_aquatic freshwater lays_eggs tiny"],
  ["toad", "toad", "kara kurbağası", "علجوم", "amphibian predator four_legs freshwater lays_eggs tiny"],
  ["salamander", "salamander", "semender", "سمندر", "amphibian predator four_legs semi_aquatic freshwater lays_eggs tiny regenerates_limbs"],
  ["axolotl", "axolotl", "aksolotl", "أكسولوتل", "amphibian predator four_legs mainly_aquatic freshwater lays_eggs tiny regenerates_limbs"],
  ["shark", "shark", "köpek balığı", "قرش", "fish predator scales marine mainly_aquatic large"],
  ["ray", "stingray", "vatoz", "شفنين", "fish predator marine mainly_aquatic venomous large"],
  ["goldfish", "goldfish", "japon balığı", "سمكة ذهبية", "fish domesticated omnivore scales freshwater mainly_aquatic tiny lays_eggs"],
  ["clownfish", "clownfish", "palyaço balığı", "سمكة المهرج", "fish omnivore scales marine mainly_aquatic tiny stripes lays_eggs"],
  ["seahorse", "seahorse", "denizatı", "فرس البحر", "fish predator marine mainly_aquatic tiny"],
  ["pufferfish", "pufferfish", "balon balığı", "سمكة منتفخة", "fish predator scales marine mainly_aquatic spines"],
  ["anglerfish", "anglerfish", "fener balığı", "سمكة الصياد", "fish predator marine mainly_aquatic tiny bioluminescent"],
  ["electric-eel", "electric eel", "elektrikli yılan balığı", "أنقليس كهربائي", "fish predator freshwater mainly_aquatic electric large"],
  ["octopus", "octopus", "ahtapot", "أخطبوط", "mollusk predator marine mainly_aquatic no_legs tentacles color_change"],
  ["squid", "squid", "kalamar", "حبار", "mollusk predator marine mainly_aquatic no_legs tentacles"],
  ["snail", "snail", "salyangoz", "حلزون", "mollusk herbivore shell no_legs slow tiny"],
  ["jellyfish", "jellyfish", "denizanası", "قنديل البحر", "predator marine mainly_aquatic no_legs tentacles venomous"],
  ["starfish", "starfish", "denizyıldızı", "نجم البحر", "predator marine mainly_aquatic no_legs regenerates_limbs slow"],
  ["crab", "crab", "yengeç", "سلطعون", "crustacean omnivore marine semi_aquatic exoskeleton claws"],
  ["lobster", "lobster", "ıstakoz", "كركند", "crustacean omnivore marine mainly_aquatic exoskeleton claws large"],
  ["shrimp", "shrimp", "karides", "روبيان", "crustacean omnivore marine mainly_aquatic exoskeleton tiny"],
  ["spider", "spider", "örümcek", "عنكبوت", "arachnid predator eight_legs exoskeleton venomous tiny"],
  ["scorpion", "scorpion", "akrep", "عقرب", "arachnid predator eight_legs exoskeleton venomous claws tiny"],
  ["ant", "ant", "karınca", "نملة", "insect omnivore six_legs exoskeleton tiny"],
  ["bee", "bee", "arı", "نحلة", "insect herbivore six_legs exoskeleton flies venomous tiny"],
  ["butterfly", "butterfly", "kelebek", "فراشة", "insect herbivore six_legs exoskeleton flies tiny"],
  ["mosquito", "mosquito", "sivrisinek", "بعوضة", "insect predator six_legs exoskeleton flies tiny"],
  ["ladybug", "ladybug", "uğur böceği", "دعسوقة", "insect predator six_legs exoskeleton flies tiny spots"],
  ["firefly", "firefly", "ateş böceği", "يراعة", "insect omnivore six_legs exoskeleton flies tiny bioluminescent"],
  ["cockroach", "cockroach", "hamam böceği", "صرصور", "insect omnivore six_legs exoskeleton tiny", "flies"],
  ["dragonfly", "dragonfly", "yusufçuk", "يعسوب", "insect predator six_legs exoskeleton flies semi_aquatic tiny"],
  ["tyrannosaurus", "Tyrannosaurus rex", "T-Rex", "تيرانوصور", "extinct reptile predator scales two_legs gigantic"],
  ["triceratops", "Triceratops", "Triseratops", "تريسيراتوبس", "extinct reptile herbivore scales four_legs horns gigantic"],
  ["stegosaurus", "Stegosaurus", "Stegozor", "ستيغوصورس", "extinct reptile herbivore scales four_legs spines gigantic"],
  ["brachiosaurus", "Brachiosaurus", "Brakiyozor", "براكيوصور", "extinct reptile herbivore four_legs long_neck gigantic"],
  ["velociraptor", "Velociraptor", "Velosiraptor", "فيلوسيرابتور", "extinct reptile predator feathers two_legs claws large"],
  ["dodo", "dodo", "dodo", "دودو", "extinct bird herbivore feathers two_legs flightless_bird lays_eggs large"],
  ["woolly-mammoth", "woolly mammoth", "yünlü mamut", "ماموث صوفي", "extinct mammal herbivore fur four_legs trunk gigantic"],
  ["saber-toothed-cat", "saber-toothed cat", "kılıç dişli kaplan", "قط سيفي الأسنان", "extinct mammal predator fur four_legs cat_family claws large"],
];

function parseTags(value = "") {
  return new Set(value.split(/\s+/).filter(Boolean));
}

export const ANIMALS: readonly AnimalProfile[] = rows.map(
  ([id, en, tr, ar, tags, uncertainTags = "", prior = 1]) => ({
    id,
    name: { en, tr, ar },
    tags: parseTags(tags),
    uncertainTags: parseTags(uncertainTags),
    prior,
  }),
);

export function traitLikelihood(animal: AnimalProfile, traitId: string): number {
  if (animal.tags.has(traitId)) return 0.97;
  if (animal.uncertainTags.has(traitId)) return 0.68;
  return 0.03;
}

export function localizedName(animal: AnimalProfile, language: Language) {
  return animal.name[language] || animal.name.en;
}
